export const langs = [
    {title: "javascript"},
    {title: "Golang"},
    {title: "Java"},
    {title: "C#"},
    {title: "C++"},
    {title: "C"},
    {title: "Node"},
    {title: "PHP"},
    {title: "React"},
    {title: "Angular"},
    {title: "Vue"},
    {title: "Git"},
    {title: "Git/Github"},
    {title: "Gitlab"},
    {title: "Docker"},
    {title: "AWS"},
    {title: "SpringBoot"},
    {title: "NextJS"},
    {title: "React Native"},
    {title: "Typescript"},
    {title: "Lua"},
    {title: "Unity"},
    {title: "API"},
    {title: "Express"},
    {title: ".NET"},
];